### ISSUE TITLE
Default docker-compose `version` to latest

### ISSUE THREAD

**Issue by ZitRos** [KengoTODA/actions-setup-docker-compose#467]
Right now, you always need to provide `version` of docker-compose when using this action:

```yaml
  steps:
  - uses: KengoTODA/actions-setup-docker-compose@main
    with:
      version: '1.29.2'
```

It is suggested to default it to "latest", by still keeping it configurable for those who need to fix the version for any reason.
