### ISSUE TITLE
Unable to prepare context on formerly working build?

### ISSUE THREAD

**Issue by adair-kovac** [KengoTODA/actions-setup-docker-compose#890]
Hi, I have a build that used to work using this step:

```
    - uses: KengoTODA/actions-setup-docker-compose@main
      with:
        version: '2.14.2'
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
        docker compose -f docker/docker-compose.yaml build
```
(Note - I was running version 1.29.2 before. Updating doesn't seem to have impacted the error one way or the other).

Now it's failing:

```
Run docker compose -f docker/docker-compose.yaml build
unable to prepare context: path "/home/runner/work/akff-php-api/akff-php-api/akff-php-api" not found
```

Where akff-php-api is the name of the project. I'm not specifying this triple-repeat directory name anywhere.

Some of the previous logs are perhaps relevant:

```
Run actions/checkout@v3
Syncing repository: mesowx/akff-php-api
Getting Git version info
Temporarily overriding HOME='/home/runner/work/_temp/1a3b09dc-686e-444f-9ed0-a83b70356434' before making global git config changes
Adding repository directory to the temporary git global config as a safe directory
/usr/bin/git config --global --add safe.directory /home/runner/work/akff-php-api/akff-php-api
Deleting the contents of '/home/runner/work/akff-php-api/akff-php-api'
Initializing the repository
Disabling automatic garbage collection
Setting up auth
Fetching the repository
Determining the checkout info
Checking out the ref
/usr/bin/git log -1 --format='%H'
'4172eb1b758cd1817b1b902375f3b2ce0039087f'
```

You can see that the actions/checkout@v3 step at some point mentions it's deleting the contents of the parent directory `/home/runner/work/akff-php-api/akff-php-api` of the directory that the build is failing on not being found. This seems like a possible smoking gun but I don't know how any of the guts are supposed to work here, hoping someone can weigh in!
